#####################################
# ImplementAndTestETLPipeline.py
#####################################
# Description:
# * Using updated DynamicETL.Service appsettings-template.json 
# file generated by "ValidateAndAppendNewETL.py" script:
# 1) Open test version of WebAPI, execute post request using sample data file to test
# ETL pipeline on local MetricsDYETL database. 
# 2) Query local MetricsDYETL database, compare uploaded contents to original sample file,
# account for discrepencies or exceptions thrown by DynamicETL.Service.

import json

def ImplementAndTestETLPipeline():
    # Pull script attributes:
    args = json.load(open())


if __name__ == "__main__":
    ImplementAndTestETLPipeline()
